// Copyright (c) 2026 — JNI bridge for the CSPP memtable Java config.
//
// Compiled only when WITH_CSPP_MEMTABLE=1 (see Makefile). When the gate is
// off, librocksdbjni.so won't export this symbol and the Java class's
// native method call will fail with UnsatisfiedLinkError.

#include <jni.h>

#include <memory>

#include "include/org_rocksdb_CSPPMemTableConfig.h"  // generated by javac
#include "rocksdb/memtablerep.h"
#include "rocksdb/write_buffer_manager.h"

/*
 * Class:     org_rocksdb_CSPPMemTableConfig
 * Method:    newMemTableFactoryHandle0
 * Signature: (JZJ)J
 */
jlong Java_org_rocksdb_CSPPMemTableConfig_newMemTableFactoryHandle0(
    JNIEnv* /*env*/, jobject /*jobj*/, jlong jmem_cap,
    jboolean jread_by_writer_token, jlong jwbm_handle) {
  size_t mem_cap = jmem_cap > 0 ? static_cast<size_t>(jmem_cap) : 0;
  bool read_by_writer_token = (jread_by_writer_token == JNI_TRUE);
  ROCKSDB_NAMESPACE::WriteBufferManager* wbm = nullptr;
  if (jwbm_handle != 0) {
    auto* sp = reinterpret_cast<
        std::shared_ptr<ROCKSDB_NAMESPACE::WriteBufferManager>*>(jwbm_handle);
    wbm = sp->get();
  }
  return reinterpret_cast<jlong>(ROCKSDB_NAMESPACE::NewCSPPMemTableRepFactory(
      mem_cap, read_by_writer_token, wbm));
}
